blank_issues_enabled: false
contact_links:
  - name: Question / discussion
    url: https://github.com/ImFelipeOliveira/hyprland-monitors/discussions
    about: Ask questions and discuss ideas before opening an issue
